#!/bin/bash
mkdir -p $JAVA_SECURITY_KEYSTORE_HOME
if [ ! -f "$JAVA_SECURITY_KEYSTORE_PATH" ]; then
  cp -rf "$JAVA_HOME/jre/lib/security/cacerts" "$JAVA_SECURITY_KEYSTORE_PATH"
fi

mkdir -p $JENKINS_HOME
mkdir -p $MAVEN_REPO
export JENKINS_DOT_M2="$JENKINS_HOME/.m2"
mkdir -p "$JENKINS_DOT_M2"

if [ ! -d "$JENKINS_HOME/.bashrc" ]; then
  cp /root/.bashrc $JENKINS_HOME/
  cat <<EOF >> $JENKINS_HOME/.bashrc
export HOME="$JENKINS_HOME"
export USER="jenkins"
export PATH=${MAVEN_HOME}/bin:$PATH
export JAVA_OPTS="$JAVA_OPTS -Djavax.net.ssl.trustStore=${JAVA_SECURITY_KEYSTORE_PATH}"
export MAVEN_OPTS="$MAVEN_OPTS -Djavax.net.ssl.trustStore=${JAVA_SECURITY_KEYSTORE_PATH}"
EOF
fi

files=$(shopt -s nullglob dotglob; echo $SSL_CERTIFICATES_HOME/*.crt)
if (( ${#files} ))
then
  echo "Some *.crt files found to import"
else
  echo "No *.crt files found to import"
  NO_CRT_FILES="true"
fi

# importing certificate files into system and jvm
if [ -z "$NO_CRT_FILES" ]; then
  echo "Importing SSL certificates to keystore $JAVA_SECURITY_KEYSTORE_PATH ..."
  mkdir -p "$SSL_CERTIFICATES_HOME/imported"
  for f in $SSL_CERTIFICATES_HOME/*.crt; do
    fname=$(basename "$f")
    fbasename="${fname%.*}"
    cp "$f" "$SSL_CERTIFICATES_DEST_HOME" && \
    $JAVA_HOME/bin/keytool -import -storepass changeit -trustcacerts -noprompt -alias $fbasename -file $f -keystore $JAVA_SECURITY_KEYSTORE_PATH && \
    mv "$f" "$SSL_CERTIFICATES_HOME/imported/" && \
    gzip -9 $SSL_CERTIFICATES_HOME/imported/$fname && \
    printf "\n=== Successfully imported $f\n" || \
    printf "\n=== Error while importing $f\n"
    echo
  done
fi

export JAVA_OPTS="$JAVA_OPTS -Djavax.net.ssl.trustStore=$JAVA_SECURITY_KEYSTORE_PATH"
export MAVEN_OPTS="$MAVEN_OPTS -Djavax.net.SSLl.trustStore=$JAVA_SECURITY_KEYSTORE_PATH"

. /usr/local/bin/jenkins.sh