#!/bin/bash
mkdir -p $JAVA_SECURITY_KEYSTORE_HOME
cp -rf "$JAVA_HOME/jre/lib/security/cacerts" "$JAVA_SECURITY_KEYSTORE_PATH"

mkdir -p $JENKINS_HOME
mkdir -p $MAVEN_REPO
export JENKINS_DOT_M2="$JENKINS_HOME/.m2"
mkdir -p "$JENKINS_DOT_M2"

if [ ! -d "$JENKINS_HOME/.bashrc" ]; then
  cp /root/.bashrc $JENKINS_HOME/
  cat <<EOF >> $JENKINS_HOME/.bashrc
export HOME="$JENKINS_HOME"
export USER="${user}"
export PATH=${MAVEN_HOME}/bin:$PATH
EOF
fi

[ "$(ls -A $SSL_CERTIFICATES_HOME)" ] && : || NO_CRT_FILES="true"

# importing certificate files into system and jvm
if [ -z "$NO_CRT_FILES" ]; then
  echo "Importing SSL certificates to keystore $JAVA_SECURITY_KEYSTORE_PATH ..."
  mkdir -p "$SSL_CERTIFICATES_HOME/imported"
  for f in $SSL_CERTIFICATES_HOME/*.crt; do
    fname=$(basename "$f")
    fbasename="${fname%.*}"
    cp "$f" "$SSL_CERTIFICATES_DEST_HOME" && \
    $JAVA_HOME/bin/keytool -import -storepass changeit -trustcacerts -noprompt -alias $fbasename -file $f -keystore $JAVA_SECURITY_KEYSTORE_PATH && \
    mv "$f" "$SSL_CERTIFICATES_HOME/imported/" && \
    gzip -9 $SSL_CERTIFICATES_HOME/imported/$fname && \
    printf "\n=== Successfully imported $f\n" || \
    printf "\n=== Error while importing $f\n"
    echo
  done
fi

export JAVA_ARGS="$JAVA_ARGS -Djavax.net.ssl.trustStore=$JAVA_SECURITY_KEYSTORE_PATH"

. /usr/local/bin/jenkins.sh